# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages
r:
  - release
  - devel
r_binary_packages:
  - dplyr,
  - magrittr,
  - readr,
  - rtracklayer,
  - stringr,
  - Biostrings,
  - BSgenome,
  - stringi,
  - DESeq2,
  - edgeR,
  - GenomicRanges,
  - IRanges,
  - seqinr,
  - R.utils,
  - reshape2,
  - ggplot2,
  - utils,
  - BiocManager,
  - rlang,
  - S4Vectors,
  - stats,
  - AnnotationHub,
  - GenomeInfoDb,
  - gwascat
